# Generated by Django 5.2.5 on 2025-12-07 01:36

import django.core.validators
import empleado.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('rut_empleado', models.CharField(error_messages={'unique': 'El rut ingresado ya se encuentra registrado, Por favor, verifique.'}, max_length=10, validators=[empleado.models.Empleado.validacion_rut_real], verbose_name='Rut (01234567-k)')),
                ('nombre_empleado', models.CharField(max_length=20, validators=[empleado.models.Empleado.validacion_nombre_y_apellido_real, django.core.validators.MinLengthValidator(3, message='Por favor, ingrese un nombre real')], verbose_name='Nombre del empleado')),
                ('apellido_empleado', models.CharField(max_length=55, validators=[empleado.models.Empleado.validacion_nombre_y_apellido_real, django.core.validators.MinLengthValidator(3, message='Por favor, ingrese un apellido real')], verbose_name='Apellido del empleado')),
                ('edad_empleado', models.IntegerField(validators=[empleado.models.Empleado.validacion_edad_negativa, django.core.validators.MinValueValidator(18, message='Debes tener al menos 18 años'), django.core.validators.MaxValueValidator(99, message='Edad invalida, no puede tener mas de 100 años')], verbose_name='Edad')),
                ('numero_telefonico', models.IntegerField(validators=[empleado.models.Empleado.validacion_largo_y_solo_numeros], verbose_name='Telefono (912345678)')),
            ],
            options={
                'db_table': 'Empleado',
                'constraints': [models.UniqueConstraint(fields=('id_empleado',), name='unique_id_empleado'), models.UniqueConstraint(fields=('rut_empleado',), name='unique_rut_empleado')],
            },
        ),
    ]
